# Generated by Django 5.0 on 2023-12-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('P', 'Purchaser'), ('V', 'Vendor')], default='', max_length=1),
        ),
    ]
