# Generated by Django 5.0 on 2023-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='acknowledgement_date',
            new_name='acknowledged_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='autual_delevery_date',
            new_name='actual_delivered_date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='expected_delevery_date',
            new_name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issued_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('C', 'Canceled'), ('P', 'Pending'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
